-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 11:52:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema donkey_event_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema donkey_event_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `donkey_event_db` DEFAULT CHARACTER SET utf8 ;
USE `donkey_event_db` ;

-- -----------------------------------------------------
-- Table `donkey_event_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Venue` (
  `idVenue` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `City_idCity` INT NOT NULL,
  PRIMARY KEY (`idVenue`, `City_idCity`),
  INDEX `fk_Venue_City_idx` (`City_idCity` ASC) VISIBLE,
  CONSTRAINT `fk_Venue_City`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `donkey_event_db`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `cover` BLOB NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Session` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `Venue_idVenue` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  `price` FLOAT NULL,
  `capacity` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`idSession`, `Venue_idVenue`, `Event_idEvent`),
  INDEX `fk_Session_Venue1_idx` (`Venue_idVenue` ASC) VISIBLE,
  INDEX `fk_Session_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  CONSTRAINT `fk_Session_Venue1`
    FOREIGN KEY (`Venue_idVenue`)
    REFERENCES `donkey_event_db`.`Venue` (`idVenue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `donkey_event_db`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Reservation` (
  `User_idUser` INT NOT NULL,
  `Session_idSession` INT NOT NULL,
  `ticketsQuantity` INT NULL,
  `insurance` INT NULL,
  PRIMARY KEY (`User_idUser`, `Session_idSession`),
  INDEX `fk_User_has_Session_Session1_idx` (`Session_idSession` ASC) VISIBLE,
  INDEX `fk_User_has_Session_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Session_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `donkey_event_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Session_Session1`
    FOREIGN KEY (`Session_idSession`)
    REFERENCES `donkey_event_db`.`Session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Artist` (
  `idArtist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `donkey_event_db`.`Performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `donkey_event_db`.`Performance` (
  `Event_idEvent` INT NOT NULL,
  `Artist_idArtist` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Event_idEvent`, `Artist_idArtist`, `Genre_idGenre`),
  INDEX `fk_Event_has_Artist_Artist1_idx` (`Artist_idArtist` ASC) VISIBLE,
  INDEX `fk_Event_has_Artist_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  INDEX `fk_Performance_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  CONSTRAINT `fk_Event_has_Artist_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `donkey_event_db`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Artist_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `donkey_event_db`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Performance_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `donkey_event_db`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
